services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
  mysql:
    image: mysql:8.0
    container_name: supplychainx-db
    environment:
      MYSQL_DATABASE: supplychainx
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - supplychainx-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supplychainx-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/supplychainx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - supplychainx-network

volumes:
  mysql-data:

networks:
  supplychainx-network:
    driver: bridge
